INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Myra","26-10-18","In.at@loremeumetus.edu","P.O. Box 752, 7560 Purus, Av.","60802");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Russell","28-05-18","morbi.tristique.senectus@orci.net","Ap #748-2796 Ac St.","39-194");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Amaya","29-01-19","enim.Nunc@auguescelerisquemollis.co.uk","9548 Consectetuer Ave","03194-909");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Melanie","30-09-18","lacus@vitaenibhDonec.ca","7930 Ligula. Road","50819");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Kiona","03-09-19","sollicitudin@dapibus.edu","P.O. Box 149, 6054 Est. Street","20829");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Willow","08-02-19","eget@aarcu.ca","Ap #164-4657 Metus Rd.","S2I 1CZ");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Hall","18-04-19","auctor.odio.a@Aliquamerat.net","720-4883 Tellus. St.","69733");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Tanner","06-09-18","facilisis.vitae.orci@dictummagnaUt.net","P.O. Box 669, 3917 Ac Rd.","11422");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Jin","03-03-19","vehicula.risus.Nulla@congueturpis.net","194-2965 Dapibus Avenue","01662");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Cooper","27-01-18","ante.Vivamus@adipiscing.edu","Ap #867-3265 Neque Street","921282");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Chester","18-12-17","felis.eget.varius@et.com","Ap #995-8817 Sociosqu Avenue","58142");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Bert","15-04-18","orci@fringillaestMauris.net","966-5525 Vitae, Av.","41047");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Ronan","07-08-18","ultricies@duiCras.org","P.O. Box 411, 4536 Mattis. Street","8898");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Tobias","15-03-18","dolor.sit.amet@aptenttacitisociosqu.org","Ap #828-9149 Est. Avenue","83718");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Lana","17-05-19","elit.Aliquam.auctor@Aliquam.net","332-4958 Aliquam Avenue","7202");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Audrey","14-07-19","magna.Cras@lectus.com","369-6892 In Avenue","9180");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Griffith","18-11-17","vitae.velit.egestas@ultricesposuere.org","5570 Leo. St.","AX3 6BD");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Fuller","26-07-19","ultrices.mauris@Donecegestas.edu","Ap #883-6652 Commodo Rd.","97693");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Jena","18-04-18","et.libero.Proin@euenim.co.uk","7952 Cursus. Street","8285");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Damon","26-03-19","consectetuer@egestas.ca","P.O. Box 686, 2699 Egestas. Street","29047");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Edward","07-11-17","ante.Nunc@urnaNunc.ca","234-6008 Fusce Rd.","55204");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Lee","15-01-18","augue.id@enimnon.edu","939-8710 Sociis Rd.","S2R 4E2");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Yael","14-09-17","Proin@eratnonummy.co.uk","444-9605 Sagittis Road","5039");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Cailin","29-06-18","faucibus.id@est.ca","P.O. Box 508, 8442 Venenatis Rd.","4477 SD");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Malik","28-02-18","convallis.est.vitae@Intinciduntcongue.ca","P.O. Box 820, 3843 Iaculis St.","71914");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Harriet","07-03-18","erat.volutpat@quislectusNullam.com","P.O. Box 993, 8646 Semper Rd.","1461");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Tarik","05-08-19","purus.Duis.elementum@risus.org","9057 Erat Rd.","WS58 7IB");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Lee","18-02-18","erat@nonummyacfeugiat.co.uk","567-3175 Nibh Road","55742");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Kim","22-06-18","sit@acmetus.net","Ap #705-1294 Justo. Road","8422");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Angela","17-07-18","mauris@utnisi.co.uk","4414 Proin Avenue","50509");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Bertha","25-07-19","a.mi.fringilla@leoCrasvehicula.edu","943-1032 Consectetuer Road","47591");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Camilla","13-04-19","Nunc.quis@interdumfeugiatSed.edu","399-5149 At Av.","139988");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Melinda","27-05-18","In.scelerisque@diamnunc.co.uk","1761 A Rd.","6774");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Neville","19-12-17","mus@commodohendrerit.edu","Ap #352-4817 Eleifend Street","U24 3VE");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Amela","07-07-18","in.hendrerit.consectetuer@vitaesodalesnisi.ca","P.O. Box 349, 8336 In Ave","6715");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Emily","21-11-18","sit.amet@varius.edu","393-8660 Commodo Ave","41164");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Devin","27-08-18","eros.turpis@diam.com","3211 Duis Rd.","31606");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Chase","10-06-19","orci@liberoet.co.uk","913-7123 Metus Ave","59705-620");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Ora","17-05-19","fermentum@turpisnec.ca","Ap #960-4488 Aliquet. Av.","98962");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Idona","08-05-19","massa.Vestibulum@acturpis.org","P.O. Box 546, 7072 Pellentesque Rd.","80157-274");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Mia","14-06-18","facilisis.non@nunc.co.uk","935-5930 Cras Street","06105");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Lionel","19-11-17","augue@loremipsum.org","P.O. Box 519, 4750 Interdum. Rd.","406176");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Samantha","23-02-18","habitant.morbi.tristique@Curabituregestas.net","P.O. Box 654, 6408 Diam St.","9275");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Yvonne","22-02-19","Quisque.fringilla.euismod@congue.org","Ap #836-1543 Fusce Av.","Y7P 1W4");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Bertha","05-07-19","eleifend.nec@pharetrafelis.com","Ap #775-8903 Enim. Ave","1485");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Danielle","02-08-18","mi.felis@sitamet.org","P.O. Box 478, 5213 Aliquet, Rd.","99-356");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Blake","02-09-19","eu@egetodio.edu","666-2089 Vel, St.","6588");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Raja","04-05-19","auctor.quis.tristique@lobortisnisinibh.com","383-6633 Lorem St.","0454");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Kuame","07-08-19","mi@Aliquamultrices.org","510-783 Vitae Ave","66890");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Vaughan","26-09-18","mauris.a@nisisem.edu","P.O. Box 634, 5402 Magna. Street","8385");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Mallory","14-08-18","venenatis.lacus.Etiam@egestasurnajusto.edu","715-698 Scelerisque Road","33693");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Dillon","30-05-18","amet.ante.Vivamus@faucibusutnulla.com","Ap #854-9461 Magna Street","29596");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Breanna","01-08-19","in.aliquet@arcuCurabitur.org","P.O. Box 214, 6966 Quis Avenue","34150");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Ebony","31-08-19","turpis@Crasinterdum.co.uk","Ap #727-4195 Pellentesque. Road","16618");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Davis","21-02-19","nulla@iderat.co.uk","Ap #888-5101 Urna Street","1293");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Jorden","25-03-19","leo@elitAliquamauctor.com","Ap #139-410 Id, St.","21291");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Sophia","03-10-18","ornare.lectus.justo@etpede.ca","Ap #171-9613 Faucibus Rd.","11911-334");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Rae","20-01-19","erat@Nulla.edu","Ap #546-6015 Elit Av.","3463");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Leilani","27-03-18","dignissim@Pellentesque.org","356-8335 Iaculis St.","7066 TN");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Keaton","18-06-19","pellentesque.massa.lobortis@rhoncus.edu","5572 Nascetur Road","19778");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Griffith","02-11-18","Phasellus@enimCurabitur.co.uk","8583 Pellentesque. Street","41952");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Grace","03-12-18","Aliquam.gravida.mauris@ut.com","1651 Hendrerit. Rd.","4215");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Kelly","04-02-18","sed.facilisis.vitae@utdolor.co.uk","5443 Ultricies Street","342411");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Lee","12-05-19","nisl@sed.com","958-5914 Donec Rd.","A2T 4Z2");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Orla","29-04-18","primis.faucibus@portti.co.uk","394-3113 Elementum St.","60408");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Nell","19-02-18","purus@tellus.com","6083 Turpis Av.","00977");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Ross","27-07-19","lorem@magnis.com","Ap #825-8136 Volutpat. Ave","5799");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Hoyt","07-08-18","quam@feugiat.com","Ap #987-6915 Ullamcorper St.","9254");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Aladdin","21-04-19","orci.Phasellus@Suspendissealiquet.co.uk","P.O. Box 887, 6538 Pulvinar Rd.","515916");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Nell","09-06-18","enim.commodo@velitSedmalesuada.co.uk","121-3097 Sit Road","39953");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Carson","09-12-18","sodales.Mauris@ettristiquepellentesque.org","3800 In Street","034720");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Rose","11-03-18","nibh@etnetus.co.uk","Ap #385-6551 Sed Street","XF85 7CH");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Bertha","30-12-18","Proin.sed@vitae.edu","791-4257 Eleifend Av.","79319");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Eric","02-05-19","tristique.pharetra@ametf.org","Ap #220-1257 Nunc Avenue","66-307");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Roanna","04-02-18","nonummy@loremegetmollis.ca","4628 Phasellus Road","42709");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Ila","21-12-18","a.malesuada@Phasellusdolor.edu","1926 Sem Av.","1890");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Martena","08-05-19","eros.nec.tellus@imperdietdic.net","573 Integer Street","1294 DH");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Claire","23-06-19","auctor@orciPhasellus.co.uk","466-7891 Semper, Av.","53329-521");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Tanisha","31-03-18","nulla.at.sem@ultricies.com","652-6298 Sapien. St.","51134");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Nora","14-04-19","tellus.Phasellus.elit@Maurismolestie.edu","7613 Pellentesque St.","5209");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Harrison","22-05-19","consequat@dignissimpharetra.ca","Ap #850-4732 Quis, Av.","1341");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Randall","23-03-19","ut.pellentesque.eget@luctus.ca","Ap #543-3464 Sed, Avenue","19485");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Kimberley","13-12-18","eros.non@gravida.ca","548-8712 Quis, Av.","32226");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Graham","13-06-18","Nam.nulla.magna@Curabitur.ca","Ap #988-9180 Est St.","85924");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Ava","09-09-19","porttitor.interdum@at.org","4301 Sem, St.","36394-536");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Elton","17-06-18","ultrices@cursusdiam.org","Ap #191-8385 Magna. Rd.","20144");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Shafira","20-02-18","luctus.ipsum.leo@dui.ca","120-5193 A, Ave","62084");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Sylvester","20-06-18","id.erat.Etiam@convallisin.org","Ap #361-738 Fames St.","34-025");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Chase","17-02-18","consequat@utnullaCras.net","1671 Lobortis Rd.","26237");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Heidi","18-05-19","ligula.eu@turpis.org","P.O. Box 881, 7925 Parturient Street","90227");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Carol","07-01-19","justo.sit@inmagnaPhasellus.edu","P.O. Box 407, 7594 Orci. St.","44-009");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Evan","03-04-19","eu.metus.In@nislsem.org","111-6368 Eu Rd.","S5I 6NP");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Hedda","27-01-18","Sed.et@tinciduntorciquis.net","P.O. Box 982, 7667 Dolor. St.","7132");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Idola","27-09-18","sit.amet@ac.ca","P.O. Box 471, 3533 Amet St.","0862");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Henry","19-04-18","non.enim.Mauris@Vestibulum.co.uk","3716 Lobortis, St.","71539");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Pascale","04-09-18","Vivamus@massaMauris.co.uk","P.O. Box 400, 2833 Faucibus Av.","60007");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Gillian","15-02-18","nunc.nulla.vulputate@justofaucibus.edu","Ap #341-5622 Aliquam Av.","61515");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Lucius","15-08-19","consequat.nec.mollis@fermentumvel.ca","2957 Sit Ave","20209");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Jared","20-04-18","Sed.malesuada.augue@sitamet.edu","Ap #217-1120 Quisque Avenue","79563");
INSERT INTO `clientes` (`nome_cliente`,`data_nasc`,`email`,`endereco`,`cep`) VALUES ("Palmer","12-09-19","tempor.arcu.Vestibulum@eu.org","P.O. Box 529, 9540 Euismod Rd.","E5B 0P4");
