-- MySQL Script generated by MySQL Workbench
-- Fri 31 Aug 2018 06:11:05 PM BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`cartoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cartoes` (
  `id_cartao` INT NOT NULL,
  `idfk_cliente` INT NOT NULL,
  `cod_seg` INT NOT NULL,
  `data_vcto` DATE NOT NULL,
  PRIMARY KEY (`id_cartao`, `idfk_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(45) NOT NULL,
  `data_nasc` DATE NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `cep` INT NOT NULL,
  `` INT NULL,
  `` INT NULL,
  PRIMARY KEY (`id_cliente`),
  INDEX `fk_clientes_cartoes_idx` (`` ASC, `` ASC),
  CONSTRAINT `fk_clientes_cartoes`
    FOREIGN KEY (`` , ``)
    REFERENCES `mydb`.`cartoes` (`id_cartao` , `idfk_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`movimentacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`movimentacoes` (
  `id_mov` INT NOT NULL AUTO_INCREMENT,
  `data_mov` DATE NOT NULL,
  `valor_mov` VARCHAR(45) NOT NULL,
  `saldo_ini` VARCHAR(45) NOT NULL,
  `saldo_fim` VARCHAR(45) NOT NULL,
  `idfk_cartao` BIGINT NOT NULL,
  `idfk_cliente` INT NOT NULL,
  PRIMARY KEY (`id_mov`),
  INDEX `fk_movimentacoes_cartoes1_idx` (`idfk_cartao` ASC, `idfk_cliente` ASC),
  CONSTRAINT `fk_movimentacoes_cartoes1`
    FOREIGN KEY (`idfk_cartao` , `idfk_cliente`)
    REFERENCES `mydb`.`cartoes` (`id_cartao` , `idfk_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`saldos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`saldos` (
  `id_saldo` INT NOT NULL AUTO_INCREMENT,
  `saldo` FLOAT NULL,
  `updated_at` TIMESTAMP NULL,
  `idfk_cartao` INT NOT NULL,
  `idfk_cliente` INT NOT NULL,
  PRIMARY KEY (`id_saldo`, `idfk_cartao`, `idfk_cliente`),
  INDEX `fk_saldos_cartoes1_idx` (`idfk_cartao` ASC, `idfk_cliente` ASC),
  CONSTRAINT `fk_saldos_cartoes1`
    FOREIGN KEY (`idfk_cartao` , `idfk_cliente`)
    REFERENCES `mydb`.`cartoes` (`id_cartao` , `idfk_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


#############################################################################################
#############################################################################################
#############################################################################################

CREATE TABLE `cartoes` (
  `id_cartao` bigint(16) NOT NULL,
  `idfk_cliente` int(11) NOT NULL,
  `cod_seg` int(11) NOT NULL,
  `data_vcto` date NOT NULL,
  `saldo` double NOT NULL,
  PRIMARY KEY (`id_cartao`,`idfk_cliente`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `clientes` (
  `id_cliente` int(11) NOT NULL AUTO_INCREMENT,
  `nome_cliente` varchar(45) NOT NULL,
  `data_nasc` date NOT NULL,
  `email` varchar(45) NOT NULL,
  `endereco` varchar(45) NOT NULL,
  `cep` varchar(16) NOT NULL,
  PRIMARY KEY (`id_cliente`)
) ENGINE=InnoDB AUTO_INCREMENT=01 DEFAULT CHARSET=latin1;

CREATE TABLE `movimentacoes` (
  `id_mov` int(11) NOT NULL AUTO_INCREMENT,
  `data_mov` date NOT NULL,
  `valor_mov` varchar(45) NOT NULL,
  `idfk_cartao` bigint(20) NOT NULL,
  `idfk_cliente` int(11) NOT NULL,
  PRIMARY KEY (`id_mov`),
  KEY `fk_movimentacoes_cartoes1_idx` (`idfk_cartao`,`idfk_cliente`),
  CONSTRAINT `fk_movimentacoes_cartoes1` FOREIGN KEY (`idfk_cartao`, `idfk_cliente`) REFERENCES `cartoes` (`id_cartao`, `idfk_cliente`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=102 DEFAULT CHARSET=latin1;

CREATE TABLE `saldos` (
  `id_saldo` int(11) NOT NULL AUTO_INCREMENT,
  `data_mov` date NOT NULL,
  `valor_mov` varchar(45) NOT NULL,
  `idfk_cartao` bigint(20) NOT NULL,
  `idfk_cliente` int(11) NOT NULL,
  PRIMARY KEY (`id_saldo`),
  KEY `fk_saldos_cartoes1_idx` (`idfk_cartao`,`idfk_cliente`),
  CONSTRAINT `fk_saldos_cartoes1` FOREIGN KEY (`idfk_cartao`, `idfk_cliente`) REFERENCES `cartoes` (`id_cartao`, `idfk_cliente`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=102 DEFAULT CHARSET=latin1;